name: Testing workflow

on: push


jobs:
   Testing -Job:
   runs-on : ubuntu-latest


   steps:
    -name: Hello display
     run: echo "HELLO WELCOME VIJAY WORLD"

    -name: Display the date
     run: date 